sudo: false
git:
  depth: 1
language: java
jdk:
- oraclejdk8
os:
- linux
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/2.*
  - rm -rf $HOME/.gradle/caches/3.0/plugin-resolution/cache.properties*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - chmod a+rx host/gradlew
  - mkdir -p ~/.gradle/
#  - echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
  - cd host
  - ./gradlew assemble --debug
script:
  - ./gradlew --stacktrace check
before_deploy:
  - ./gradlew dist
  - export RELEASE_PKG_FILE=$(ls *.zip | grep -v 298 | head -1)
  - echo "deploying $RELEASE_PKG_FILE"
deploy:
  - provider: releases
    skip_cleanup: true
    prerelease: false
    api_key: "$GITHUB_ACCESS_TOKEN"
    file_glob: true
    file: "${RELEASE_PKG_FILE}"
    on:
      tags: true
      condition: -n "$GITHUB_ACCESS_TOKEN"
#  - provider: bintray
#    file: ".bintray.yml"
#    user: $BINTRAY_USER
#    key: $BINTRAY_API_KEY
#    dry-run: $SKIP_BINTRAY
#    on:
#      all_branches: true
